WebShopAuth/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShop.DAL;
using WebShop.Model;
using WebShop.Web.ViewModels;
using WebShop.Web.Models.DTO;
using Microsoft.AspNetCore.Authorization;

namespace WebShop.Web.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private readonly WebShopDbContext _context;

        public ItemsController(WebShopDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Items.ToListAsync());
        }

        public async Task<IActionResult> Grid()
        {
            ItemsGridViewModel vm = new ItemsGridViewModel();
            vm.TagSelect = _context.Tags.Select(x => new SelectListItem { Selected = false, Text = x.Description, Value = x.Id.ToString() }).ToList();
            vm.Items = await _context.Items.Include(x => x.Tags).ToListAsync();
            return View(vm);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            CreateItemViewModel vm = new CreateItemViewModel
            {
                TagSelect = _context.Tags.Select(x => new SelectListItem { Selected = false, Text = x.Description, Value = x.Id.ToString() }).ToList()
            };
            return View(vm);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] CreateItemDto item)
        {
            Item newItem = new Item()
            {
                Description = item.Description,
                Discount = item.Discount,
                MadeAt = item.MadeAt,
                Name = item.Name,
                Price = item.Price
            };

            newItem.Tags = new List<Tag>();

            foreach (var tagId in item.TagIds)
            {
                newItem.Tags.Add(_context.Tags.FirstOrDefault(x => x.Id == tagId));
            }

            _context.Items.Add(newItem);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var item = await _context
                .Items
                .Include(x => x.Tags)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items.Include(x => x.Tags).FirstOrDefaultAsync(x => x.Id == id);

            if (item == null)
            {
                return NotFound();
            }

            CreateItemViewModel vm = new CreateItemViewModel();

            vm.Item = new UpdateItemDto()
            {
                Description = item.Description,
                Discount = item.Discount,
                Id = item.Id,
                MadeAt = item.MadeAt,
                Name = item.Name,
                Price = item.Price,
                TagIds = item.Tags.Select(x => x.Id).ToList()
            };

            vm.TagSelect = _context.Tags.Select(x => new SelectListItem
            {
                Selected = vm.Item.TagIds.Contains(x.Id),
                Text = x.Description,
                Value = x.Id.ToString()
            }).ToList();

            return View(vm);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit([FromForm]UpdateItemDto item)
        {
            if (!ItemExists(item.Id))
            {
                return NotFound();
            }

            Item foundItem = await _context.Items.Include(x => x.Tags).FirstOrDefaultAsync(x => x.Id == item.Id);
            _context.Entry(foundItem).CurrentValues.SetValues(item);

            foundItem.Tags = new List<Tag>();

            foreach (var tagId in item.TagIds)
            {
                foundItem.Tags.Add(_context.Tags.FirstOrDefault(x => x.Id == tagId));
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var item = await _context.Items
                .FirstOrDefaultAsync(m => m.Id == id);

            if (item == null)
            {
                return NotFound();
            }

            _context.Items.Remove(item);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int? id)
        {
            if (id == null)
            {
                return false;
            }

            return _context.Items.Any(e => e.Id == id);
        }
    }
}

WebShopAuth/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShop.DAL;
using WebShop.Model;
using Microsoft.AspNetCore.Authorization;

namespace WebShop.Web.Views
{
    [Authorize(Roles = "Admin")]
    [Authorize]
    public class TagsController : Controller
    {
        private readonly WebShopDbContext _context;

        public TagsController(WebShopDbContext context)
        {
            _context = context;
        }

        [Route("tag-list")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tags.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags.FindAsync(id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description")] Tag tag)
        {
            if (id != tag.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TagExists(tag.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var tag = await _context.Tags.FindAsync(id);
            _context.Tags.Remove(tag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagExists(int id)
        {
            return _context.Tags.Any(e => e.Id == id);
        }
    }
}

WebShopAuth/Views/Shared/_EditOrCreateItemForm.cshtml
@model WebShop.Web.ViewModels.CreateItemViewModel

<input hidden asp-for="Item.Id" />
<div class="form-group">
    <label asp-for="Item.Name" class="control-label"></label>
    <input asp-for="Item.Name" class="form-control" />
    <span asp-validation-for="Item.Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Item.Description" class="control-label"></label>
    <input asp-for="Item.Description" class="form-control" />
    <span asp-validation-for="Item.Description" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Item.Price" class="control-label"></label>
    <input asp-for="Item.Price" class="form-control" />
    <span asp-validation-for="Item.Price" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Item.Discount" class="control-label"></label>
    <input asp-for="Item.Discount" class="form-control" />
    <span asp-validation-for="Item.Discount" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Item.TagIds" class="control-label"></label>
    <select multiple asp-for="Item.TagIds" asp-items="@Model.TagSelect" class="form-control"></select>
    <span asp-validation-for="Item.TagIds" class="text-danger"></span>
</div>
<div class="form-group">
    <label class="control-label">Made at</label>
    <div class="input-group date" data-provide="datepicker" data-date-format="@System.Threading.Thread.CurrentThread.CurrentCulture.DateTimeFormat.ShortDatePattern.ToLower()">
        <input asp-for="Item.MadeAt" type="text" class="form-control">
        <div class="input-group-addon">
            <span class="glyphicon glyphicon-th"></span>
        </div>
    </div>
    <span asp-validation-for="Item.MadeAt" class="text-danger"></span>
</div>
<div class="form-group text-right">
    <input type="submit" value="Save" class="btn btn-primary" />
</div>

WebShopAuth/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using WebShop.Model
@using WebShop.Web.Services

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager
@inject IsUserAdminService IsUserAdminService

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google-signin-client_id" content="YOUR_CLIENT_ID.apps.googleusercontent.com">
    <title>@ViewData["Title"] - WebShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-datepicker/css/bootstrap-datepicker.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Grid">Our merchandise</a>
                            </li>
                            @if (await IsUserAdminService.IsAdmin())
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">Items (Admin)</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="Index">Tags (Admin)</a>
                                </li>
                            }
                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-4">
        @RenderBody()
    </main>
    <app-footer> </app-footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-datepicker/js//bootstrap-datepicker.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>